package com.sb.db.dbase.model;
// Generated Apr 6, 2021, 9:54:39 PM by Hibernate Tools 5.4.18.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String email;
	private String password;
	private long userId_1;
	private String userName_1;

	public Users() {
	}

	public Users(String userName, String email, String password, long userId_1, String userName_1) {
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.userId_1 = userId_1;
		this.userName_1 = userName_1;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public long getUserId_1() {
		return this.userId_1;
	}

	public void setUserId_1(long userId_1) {
		this.userId_1 = userId_1;
	}

	public String getUserName_1() {
		return this.userName_1;
	}

	public void setUserName_1(String userName_1) {
		this.userName_1 = userName_1;
	}

}
